[package]
name = "andromeda-std"
version = "0.1.0"
edition = "2021"
rust-version  = "1.65.0"

[features]
withdraw = ["andromeda-macros/withdraw"]
primitive = []
modules = ["andromeda-macros/modules"]
module_hooks = ["andromeda-macros/module_hooks"]
instantiate = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace=true, features = ["ibc3"] }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
schemars = "0.8.10"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
semver = { workspace = true }
cw20 = { version = "1.0.1"}
cw20-base = { version = "1.0.1", features = ["library"] }
cw721-base = { version = "0.17.0", features = ["library"] }
cw-utils = { workspace = true }
cw-asset = { version = "3.0.0" }
thiserror = { version = "1.0.21" }
lazy_static = "1"
hex = "0.4"
andromeda-macros = { workspace = true }
strum_macros = { workspace = true }
cw721 = "0.17"
zip-optional = { git = "https://github.com/public-awesome/ics721.git" }
cw721-proxy-derive = { git = "https://github.com/0xekez/cw721-proxy.git" }
cw-cii = { git = "https://github.com/public-awesome/ics721.git" }
cw-pause-once = { git = "https://github.com/public-awesome/ics721.git" }
serde-json-wasm = "0.5.0"
