[package]
name = "andromeda-std"
version = "0.1.0"
edition = "2018"

[features]
withdraw = ["cw-asset", "andromeda-macros/withdraw"]
primitive = []
modules = ["andromeda-macros/modules"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace=true, features = ["ibc3"] }
cosmwasm-schema = "1.2.1"
cw-storage-plus = "0.16.0"
schemars = "0.8.10"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
cw2 = "0.16.0"
semver = "1"
cw20 = { version = "0.16.0"}
cw20-base = { version = "0.16.0" }
cw721-base = { version = "0.17.0" }
cw-utils = "0.16.0"
cw-asset = { version = "2.0.0", optional = true }
regex = "1"
thiserror = { version = "1.0.21" }
lazy_static = "1"
hex = "0.4"
cw1155 = "0.16.0"
cw1155-base = "0.16.0"
andromeda-macros = { workspace = true }
strum_macros = { workspace = true }
cw721 = "0.17"
zip-optional = { git = "https://github.com/public-awesome/ics721.git" }
cw721-proxy-derive = { git = "https://github.com/0xekez/cw721-proxy.git" }
cw-cii = { git = "https://github.com/public-awesome/ics721.git" }
cw-pause-once = { git = "https://github.com/public-awesome/ics721.git" }

[dev-dependencies]
cw20 = "0.16.0"
