[package]
name = "andromeda-non-fungible-tokens"
version = "0.1.0"
edition = "2018"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
cw-utils = "1.0.1"
cw721 = "0.17.0"
cw721-base = { version = "0.17.0", features=["library"]}

andromeda-std = { workspace = true, features=["modules"] }

