[package]
name = "andromeda-macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[features]
modules = []
withdraw = []
module_hooks = []

[dependencies]
syn = { version = "1.0.0", features = ["derive"]}
proc-macro2 = "1.0"
quote="1.0"

[dev-dependencies]
cw20 = "0.16.0"
