[package]
name = "andromeda-weighted-distribution-splitter"
version = "0.2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.2.1"
cosmwasm-schema = "1.2.1"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
schemars = "0.8.10"
cw-storage-plus = "0.16.0"
cw2 = "0.16.0"
cw-utils = "0.16.0"
semver = "1"

andromeda-os = { version = "0.1.0", path = "../../../packages/andromeda-os" }
andromeda-finance = { version = "0.1.0", path = "../../../packages/andromeda-finance" }
ado-base = { path = "../../../packages/ado-base", version = "0.1.0", features = ["modules"] }
common = { version = "0.1.0", path = "../../../packages/common" }
andromeda-testing = { version = "0.1.0", path = "../../../packages/andromeda-testing" }

[dev-dependencies]

andromeda-app = { version = "0.1.0", path = "../../../packages/andromeda-app" }