[package]
name = "andromeda-fungible-tokens"
version = "0.1.0"
edition = "2018"

[features]
backtraces = ["cosmwasm-std/backtraces"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "1.1.8"
getrandom = { version = "0.2", features = ["js"] }
cosmwasm-schema = "1.1.8"
serde = { version = "1.0.148", default-features = false, features = ["derive"] }
schemars = "0.8.11"
cw20 = "1.0.0"
cw-utils = "1.0.0"
cw20-base = { version = "1.0.0", features=["library"]}

common = { path = "../common", version = "0.1.0" }
cw-asset = { version = "2.0.0" }

